FROM golang as base

RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -a .

### App
FROM scratch as app

COPY --from=base /app/app /server
EXPOSE 5000
ENTRYPOINT ["./server"]
