FROM golang as base

RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

### App
FROM scratch as app

COPY --from=base /app/main /app

CMD ["/app"]
